### ISSUE TITLE
Undefined behaviour

### ISSUE THREAD

**Issue by jendrikw** [georgebarwood/btree_experiment#1]
Hi,

first of all, I got here from your posts on URLO. I appreciate your efforts. Unrelated to the discussion about the unsafety in `FixedCapVec`, I found undefined behaviour in other parts of the code. In particular, this line is wrong, because it creates a `&mut LeafVec<K, V>` which aliases with `self.map.tree`.

https://github.com/georgebarwood/btree_experiment/blob/c603b06567557597b6f0bdace63a37203c1dfacb/src/lib.rs#L803

This can be verified by running tests with miri or by simply printing some pointers. When you add the following two lines directly after, you can see the pointers overlapping.

```
println!("{:p}", self.map);
println!("{:p}", x);
```

As an example, this is the output I got on my machine: 
```
0x7a1a0e61cb50
0x7a1a0e61cb58
```
I think the 8 bytes difference is the `len:usize` of `BTreeMap`. If I understood everything correctly, the next member should then be the FixedCapVec (after a few indirections through Tree and Leaf). The problem is that at that point you have two mutable references to the same FixedCapVec, but mutable references are supposed to be unique!

**Comment by jendrikw** [comment]
Test case for miri: `btree_experiment::BTreeMap::new().entry(0).or_insert('a');`

**Comment by georgebarwood** [comment]
Thanks. I can see the potential problem regarding references. I think someone suggested it was ok in this case, but perhaps it isn't. I don't have a good understanding of the issue really. It apparently works in practice!!!! Maybe it is actually UB. I don't know.

[ I ran miri and yes, miri is unhappy ]

Maybe continue discussion here:
https://users.rust-lang.org/t/improving-efficiency-of-entry-api-for-my-btree-implementation/109467/9?u=geebee22

**Comment by georgebarwood** [comment]
I changed the code to use a raw pointer for VacantEntry.map and OccupiedEntry.map, and Miri is now happy with the test example.
